name: Automatisation des tests

on: push

jobs:
  # Étape 1: On compile le code UNE SEULE FOIS
  Compilation:
    runs-on: ubuntu-latest
    steps:
      # Action officielle pour récupérer le code de votre repository
      - name: Recuperation du code
        uses: actions/checkout@v4

      # On compile le code normalement
      - name: Compilation du projet
        run: |
          mkdir build
          cd build
          cmake ..
          make
      
      # On sauvegarde le dossier "build" complet comme un artifact
      - name: Sauvegarde de l'artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-build # Nom de notre artifact
          path: build/          # Dossier à sauvegarder

  # Étape 2: Les jobs de tests qui tournent en parallèle
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation # Dépend de la compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

      # LIGNE CORRIGÉE : On donne la permission d'exécuter le fichier
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction add
        run: ./src/calculator add 2 3

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build
      
      # LIGNE CORRIGÉE : On donne la permission d'exécuter le fichier
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator
        
      - name: Test fonction sub
        run: ./src/calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

      # LIGNE CORRIGÉE : On donne la permission d'exécuter le fichier
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction mul
        run: ./src/calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

      # LIGNE CORRIGÉE : On donne la permission d'exécuter le fichier
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction div
        run: ./src/calculator div 1 5
  
  Test_Carre:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Telechargement de l'artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-build

      # LIGNE CORRIGÉE : On donne la permission d'exécuter le fichier
      - name: Donner les permissions d'execution
        run: chmod +x ./src/calculator

      - name: Test fonction car
        run: ./src/calculator car 5

  # Étape 3: Le déploiement, qui attend la fin de TOUS les tests
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Carre]
    steps:
      - name: Déploiement de la solution
        run: echo "Tous les tests sont passés, déploiement réussi !"